//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtomalaz.DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCO_BANCOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BCO_BANCOS()
        {
            this.BCO_CUENTA_BANCOS = new HashSet<BCO_CUENTA_BANCOS>();
            this.NOM_EMPLEADOS = new HashSet<NOM_EMPLEADOS>();
        }
    
        public int Bco_Ban_Id { get; set; }
        public string Bco_Ban_Nombre { get; set; }
        public int Bco_CodFinan_Id { get; set; }
        public string Bco_Ban_Agencia { get; set; }
        public string Bco_Ban_RUC { get; set; }
        public int Gen_PrmPai_Id { get; set; }
        public int Gen_PrmPro_Id { get; set; }
        public int Gen_PrmCiu_Id { get; set; }
        public int Gen_PrmPrq_Id { get; set; }
        public string Bco_Ban_Direccion { get; set; }
        public string Bco_Ban_OficialCta { get; set; }
        public string Bco_Ban_Telefono { get; set; }
        public string Bco_Ban_Email { get; set; }
        public Nullable<int> Aud_EstadoAI_Id { get; set; }
        public Nullable<int> Aud_Usuario_Ingreso { get; set; }
        public Nullable<System.DateTime> Aud_Fecha_Ingreso { get; set; }
        public string Aud_PC_Ingreso { get; set; }
        public Nullable<int> Aud_Usuario_Modifica { get; set; }
        public Nullable<System.DateTime> Aud_Fecha_Modifica { get; set; }
        public string Aud_PC_Modifica { get; set; }
    
        public virtual GEN_PRM_GEOI_CIUDAD GEN_PRM_GEOI_CIUDAD { get; set; }
        public virtual SEG_ESTADO_AI SEG_ESTADO_AI { get; set; }
        public virtual BCO_CODIGO_FINANCIERO BCO_CODIGO_FINANCIERO { get; set; }
        public virtual SEG_USUARIO SEG_USUARIO { get; set; }
        public virtual SEG_USUARIO SEG_USUARIO1 { get; set; }
        public virtual GEN_PRM_GEOA_PAISES GEN_PRM_GEOA_PAISES { get; set; }
        public virtual GEN_PRM_GEOE_PROVINCIAS GEN_PRM_GEOE_PROVINCIAS { get; set; }
        public virtual GEN_PRM_GEOO_PARROQUIAS GEN_PRM_GEOO_PARROQUIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BCO_CUENTA_BANCOS> BCO_CUENTA_BANCOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOM_EMPLEADOS> NOM_EMPLEADOS { get; set; }
    }
}
