//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtomalaz.DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCO_CUENTA_BANCOS
    {
        public int Bco_Cta_Id { get; set; }
        public int SEG_EMPRESA_Id { get; set; }
        public int Bco_Ban_Id { get; set; }
        public int Bco_CtaTipo_Id { get; set; }
        public string Bco_Cta_Numero { get; set; }
        public System.DateTime Bco_Cta_FecApertura { get; set; }
        public int Bco_Cta_UltCheq { get; set; }
        public System.DateTime Bco_Cta_FecUltCheq { get; set; }
        public int Con_PlaCta_Id { get; set; }
        public Nullable<int> Aud_EstadoAI_Id { get; set; }
        public Nullable<int> Aud_Usuario_Ingreso { get; set; }
        public Nullable<System.DateTime> Aud_Fecha_Ingreso { get; set; }
        public string Aud_PC_Ingreso { get; set; }
        public Nullable<int> Aud_Usuario_Modifica { get; set; }
        public Nullable<System.DateTime> Aud_Fecha_Modifica { get; set; }
        public string Aud_PC_Modifica { get; set; }
    
        public virtual BCO_BANCOS BCO_BANCOS { get; set; }
        public virtual SEG_EMPRESA SEG_EMPRESA { get; set; }
        public virtual SEG_ESTADO_AI SEG_ESTADO_AI { get; set; }
        public virtual SEG_USUARIO SEG_USUARIO { get; set; }
        public virtual SEG_USUARIO SEG_USUARIO1 { get; set; }
        public virtual CON_CUENTA_PLAN CON_CUENTA_PLAN { get; set; }
        public virtual BCO_CUENTA_TIPO BCO_CUENTA_TIPO { get; set; }
    }
}
