//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtomalaz.DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_CAB_ORDEN
    {
        public int CAB_Orden_Cab_Id { get; set; }
        public int EMP_Id_Empresa { get; set; }
        public string SOL_Id_Solicitud { get; set; }
        public int ENT_Id_PEntidad { get; set; }
        public int ENT_Id_Entidad { get; set; }
        public System.DateTime CAB_FechaPedido { get; set; }
        public System.DateTime CAB_FechaEmitida { get; set; }
        public string CAB_Estado { get; set; }
        public string CAB_Hora { get; set; }
        public string CAB_Observacion { get; set; }
        public double CAB_Descuento { get; set; }
        public double CAB_Iva { get; set; }
        public double CAB_Total { get; set; }
        public double CAB_Ajuste { get; set; }
        public string CAB_Prioridad { get; set; }
        public int CAB_Tipo_Producto { get; set; }
        public Nullable<int> Aud_EstadoAI_Id { get; set; }
        public Nullable<int> Aud_Usuario_Ingreso { get; set; }
        public Nullable<System.DateTime> Aud_Fecha_Ingreso { get; set; }
        public string Aud_PC_Ingreso { get; set; }
        public Nullable<int> Aud_Usuario_Modifica { get; set; }
        public Nullable<System.DateTime> Aud_Fecha_Modifica { get; set; }
        public string Aud_PC_Modifica { get; set; }
    
        public virtual SEG_EMPRESA SEG_EMPRESA { get; set; }
        public virtual SEG_ESTADO_AI SEG_ESTADO_AI { get; set; }
        public virtual SEG_USUARIO SEG_USUARIO { get; set; }
        public virtual SEG_USUARIO SEG_USUARIO1 { get; set; }
    }
}
