//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtomalaz.DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class CON_DIARIO_CAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CON_DIARIO_CAB()
        {
            this.CON_DIARIO_AUX = new HashSet<CON_DIARIO_AUX>();
            this.CON_DIARIO_DET = new HashSet<CON_DIARIO_DET>();
        }
    
        public int Con_DiarioCab_Id { get; set; }
        public int Gen_PrmAnio_Id { get; set; }
        public int Gen_PrmMes_Id { get; set; }
        public int SEG_EMPRESA_Id { get; set; }
        public int Con_CompTip_Id { get; set; }
        public string Con_DiarioCab_Numero { get; set; }
        public System.DateTime Con_DiarioCab_Fecha_Contable { get; set; }
        public string Con_DiarioCab_Diario_Nombre { get; set; }
        public string Con_DiarioCab_Diario_Descripcion { get; set; }
        public int Con_EstCont_Id { get; set; }
        public decimal Con_DiarioCab_Total_Debe { get; set; }
        public decimal Con_DiarioCab_Total_Haber { get; set; }
        public System.DateTime Con_DiarioCab_Digitado_Fecha { get; set; }
        public string Con_DiarioCab_Digitado_Usuario { get; set; }
        public System.DateTime Con_DiarioCab_Procesado_Fecha { get; set; }
        public string Con_DiarioCab_Procesado_Usuario { get; set; }
        public string Con_DiarioCab_Reg_T_P { get; set; }
        public Nullable<int> Aud_EstadoAI_Id { get; set; }
        public Nullable<int> Aud_Usuario_Ingreso { get; set; }
        public Nullable<System.DateTime> Aud_Fecha_Ingreso { get; set; }
        public string Aud_PC_Ingreso { get; set; }
        public Nullable<int> Aud_Usuario_Modifica { get; set; }
        public Nullable<System.DateTime> Aud_Fecha_Modifica { get; set; }
        public string Aud_PC_Modifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CON_DIARIO_AUX> CON_DIARIO_AUX { get; set; }
        public virtual GEN_ANIO GEN_ANIO { get; set; }
        public virtual SEG_EMPRESA SEG_EMPRESA { get; set; }
        public virtual SEG_ESTADO_AI SEG_ESTADO_AI { get; set; }
        public virtual CON_ESTADO_CONTAB CON_ESTADO_CONTAB { get; set; }
        public virtual SEG_USUARIO SEG_USUARIO { get; set; }
        public virtual GEN_MES GEN_MES { get; set; }
        public virtual SEG_USUARIO SEG_USUARIO1 { get; set; }
        public virtual CON_DIARIO_TIPO CON_DIARIO_TIPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CON_DIARIO_DET> CON_DIARIO_DET { get; set; }
    }
}
