//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtomalaz.DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_EMPLEADOS
    {
        public int Nom_Epd_Id { get; set; }
        public int SEG_EMPRESA_Id { get; set; }
        public int Gen_TipIden_Id { get; set; }
        public string Nom_Epd_Documento { get; set; }
        public string Nom_Epd_Nombre1 { get; set; }
        public string Nom_Epd_Nombre2 { get; set; }
        public string Nom_Epd_Apellido1 { get; set; }
        public string Nom_Epd_Apellido2 { get; set; }
        public string Nom_Epd_Mail_Personal { get; set; }
        public string Nom_Epd_Mail_Empresa { get; set; }
        public int Gen_PrmCivilE_Id { get; set; }
        public string Nom_Epd_Movil { get; set; }
        public int Gen_PrmOperM_Id { get; set; }
        public System.DateTime Nom_Epd_FecNac { get; set; }
        public int Gen_PrmSex_Id { get; set; }
        public byte[] Nom_Epd_Foto { get; set; }
        public int Gen_PrmForPag_Id { get; set; }
        public int Nom_Epd_Usu_Sistema { get; set; }
        public int Nom_Epd_Discapacidad_SN { get; set; }
        public int Gen_PrmDiscaT_Id { get; set; }
        public int Nom_Epd_Discap_Porc { get; set; }
        public int Nom_Epd_Discap_Grad { get; set; }
        public int Nom_Epd_Discap_Carnet_SN { get; set; }
        public string Nom_Epd_Discap_Carnet_Num { get; set; }
        public int Nom_Epd_AsistenciaComp_SN { get; set; }
        public int Gen_PrmPai_Id { get; set; }
        public int Gen_PrmPro_Id { get; set; }
        public int Gen_PrmCiu_Id { get; set; }
        public int Gen_PrmPrq_Id { get; set; }
        public string Nom_Epd_Direccion { get; set; }
        public string Nom_Epd_Direccion_Referen { get; set; }
        public string Nom_Epd_Procedencia { get; set; }
        public int Gen_PrmEducN_Id { get; set; }
        public int Bco_Ban_Id { get; set; }
        public int Bco_CtaTipo_Id { get; set; }
        public string Nom_Epd_Banco_Cuenta { get; set; }
        public int Gen_PrmParenT_Id { get; set; }
        public string Nom_Epd_Contac_Nombre { get; set; }
        public string Nom_Epd_Contac_Apellido { get; set; }
        public string Nom_Epd_Contac_Telefono { get; set; }
        public int Nom_Epd_Contac_Tii_Id { get; set; }
        public string Nom_Epd_Contac_Documento { get; set; }
        public string Nom_Epd_Contac_Direccion { get; set; }
        public string Nom_Epd_Codigo_Reloj0 { get; set; }
        public string Nom_Epd_Codigo_Reloj1 { get; set; }
        public string Nom_Epd_Codigo_Reloj2 { get; set; }
        public string Nom_Epd_Codigo_Reloj3 { get; set; }
        public string Nom_Epd_Codigo_Reloj4 { get; set; }
        public int Nom_EpdTip_Id { get; set; }
        public byte[] Nom_Epd_Contrato { get; set; }
        public Nullable<int> Aud_EstadoAI_Id { get; set; }
        public Nullable<int> Aud_Usuario_Ingreso { get; set; }
        public Nullable<System.DateTime> Aud_Fecha_Ingreso { get; set; }
        public string Aud_PC_Ingreso { get; set; }
        public Nullable<int> Aud_Usuario_Modifica { get; set; }
        public Nullable<System.DateTime> Aud_Fecha_Modifica { get; set; }
        public string Aud_PC_Modifica { get; set; }
    
        public virtual BCO_BANCOS BCO_BANCOS { get; set; }
        public virtual BCO_CUENTA_TIPO BCO_CUENTA_TIPO { get; set; }
        public virtual GEN_PRM_DISCAPCIDA_TIPO GEN_PRM_DISCAPCIDA_TIPO { get; set; }
        public virtual GEN_PRM_EDUCACION_NIVEL GEN_PRM_EDUCACION_NIVEL { get; set; }
        public virtual GEN_PRM_ESTADO_CIVL GEN_PRM_ESTADO_CIVL { get; set; }
        public virtual GEN_PRM_FORMA_PAGO GEN_PRM_FORMA_PAGO { get; set; }
        public virtual GEN_PRM_GEOA_PAISES GEN_PRM_GEOA_PAISES { get; set; }
        public virtual GEN_PRM_GEOE_PROVINCIAS GEN_PRM_GEOE_PROVINCIAS { get; set; }
        public virtual GEN_PRM_GEOI_CIUDAD GEN_PRM_GEOI_CIUDAD { get; set; }
        public virtual GEN_PRM_GEOO_PARROQUIAS GEN_PRM_GEOO_PARROQUIAS { get; set; }
        public virtual GEN_PRM_OPERADORA_MOVIL GEN_PRM_OPERADORA_MOVIL { get; set; }
        public virtual GEN_PRM_PARENTESCO GEN_PRM_PARENTESCO { get; set; }
        public virtual GEN_PRM_SEXO GEN_PRM_SEXO { get; set; }
        public virtual GEN_TIPO_IDENTIFICACION GEN_TIPO_IDENTIFICACION { get; set; }
        public virtual GEN_TIPO_IDENTIFICACION GEN_TIPO_IDENTIFICACION1 { get; set; }
        public virtual NOM_EMPLEADO_TIPO NOM_EMPLEADO_TIPO { get; set; }
        public virtual SEG_EMPRESA SEG_EMPRESA { get; set; }
        public virtual SEG_ESTADO_AI SEG_ESTADO_AI { get; set; }
        public virtual SEG_USUARIO SEG_USUARIO { get; set; }
        public virtual SEG_USUARIO SEG_USUARIO1 { get; set; }
        public virtual SEG_ESTADO_AI SEG_ESTADO_AI1 { get; set; }
        public virtual SEG_ESTADO_AI SEG_ESTADO_AI2 { get; set; }
        public virtual SEG_ESTADO_AI SEG_ESTADO_AI3 { get; set; }
        public virtual SEG_USUARIO SEG_USUARIO2 { get; set; }
    }
}
